apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: mem
  name: mem
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: mem
    spec:
      containers:
      - image: host.io/eg_memcached
        name: mem
        ports:
        - containerPort: 11211
        resources: {}
      restartPolicy: Always
status: {}
