apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: mock
  name: mock
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: mock
    spec:
      containers:
      - image: host.io/eg_mock
        name: mock
        ports:
        - containerPort: 8081
        resources: {}
      restartPolicy: Always
status: {}
