apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: push
  name: push
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  type: LoadBalancer
  selector:
    io.kompose.service: push
status:
  loadBalancer: {}
