apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: push
  name: push
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: push
    spec:
      containers:
      - env:
        - name: HPC_APIURL
          value: http://mock:8081/api/v2
        - name: MEMCACHED_HOST
          value: mem
        - name: RABBITMQ_DEFAULT_PASS
          value: admin
        - name: RABBITMQ_DEFAULT_USER
          value: admin
        - name: RABBITMQ_HOST
          value: stats
        image: host.io/eg_pushnotif
        name: push
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
